ASPNETWebApplicationTest/Controllers/OrmLiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceStack;
using ServiceStack.Text;
using ServiceStack.OrmLite;
using ServiceStack.OrmLite.SqlServer;
using ServiceStack.DataAnnotations;
using ASPNETWebApplicationTest.Models;
using System.Configuration;
using PagedList;

namespace ASPNETWebApplicationTest.Controllers
{
    public class OrmLiteController : Controller
    {

        // GET: OrmLite
        public ActionResult Index()
        {
            //var dbFactory = new OrmLiteConnectionFactory("DefaultConnection", SqlServerDialect.Provider);
            var dbFactory = new OrmLiteConnectionFactory(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString, SqlServerDialect.Provider);
            //var db = dbFactory.OpenDbConnectionString("HumanResources.Department");     //Open ADO.NET DB Connection
            var db = dbFactory.Open();
            //db.ConnectionString = "";

            //List<HumanResourcesDepartmentModel> output = db.SelectByIds(new[] { 1, 2, 3 }).ToList();
            //int val = db.ExecuteSql("select * from HumanResources.Department");
            //db.DropAndCreateTable<SimpleModel>(); //DROP (if exist) and CREATE Table from User POCO
            //db.Insert(                     //INSERT multiple Users by params
            //    new SimpleModel { Id = 1, Name = "A"},
            //    new SimpleModel { Id = 2, Name = "B"},
            //    new SimpleModel { Id = 3, Name = "C"},
            //    new SimpleModel { Id = 4, Name = "C"});


            return View();
        }
        [HttpPost]
        public ActionResult Create(SimpleModel sm)
        {
            var dbFactory = new OrmLiteConnectionFactory(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString, SqlServerDialect.Provider);
            using (var db = dbFactory.Open())
            {
                db.Insert(sm);
            }

            sm.Name = "";
            sm.Description = "";
            return View(sm);
        }
        public ActionResult Create()
        {
            return View(new SimpleModel());
        }
        public ActionResult Details()
        {
            var dbFactory = new OrmLiteConnectionFactory(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString, SqlServerDialect.Provider);
            using (var db = dbFactory.Open())
            {
                List<SimpleModel> sm = db.Select<SimpleModel>(x => x.Name.Contains(""));
                return View(sm);
            }

        }

        public ActionResult Search()
        {
            return View(new SimpleModel());
        }
        [HttpPost]
        public ActionResult Search(SimpleModel model)
        {
            var dbFactory = new OrmLiteConnectionFactory(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString, SqlServerDialect.Provider);
            using (var db = dbFactory.Open())
            {
                SimpleModel sm = db.Single<SimpleModel>(x => x.Name.Contains(model.Name));
                return View(sm);
            }
            //return View();
        }

        public ActionResult Read()
        {
            return View();
        }    


    }
}

ASPNETWebApplicationTest/Views/OrmLite/Create.cshtml
@model ASPNETWebApplicationTest.Models.SimpleModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ASPNETWebApplicationTest/Views/OrmLite/Details.cshtml
@using ASPNETWebApplicationTest.Models

@model List<SimpleModel>

@{
    ViewBag.Title = "Details";
}
<h2>Details</h2>
<div class="form-horizontal">
    <table class="table">
        <tr>
            <th> Name </th>
            <th>Description</th>
        </tr>
        @foreach (var sm in Model)
        {
            <tr>
                <td>@sm.Name</td>
                <td>@sm.Description</td>
            </tr>
        }
    </table>
    @Html.ActionLink("Back to List", "Index")
</div>

ASPNETWebApplicationTest/Views/OrmLite/Index.cshtml
@using ASPNETWebApplicationTest.Models

@model SimpleModel
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<button class="btn btn-default">@Html.ActionLink("Read", "Read", "OrmLite")</button>
<button class="btn btn-default">@Html.ActionLink("Create", "Create", "OrmLite")</button>
<button class="btn btn-default">@Html.ActionLink("Details", "Details", "OrmLite")</button>
<button class="btn btn-default">@Html.ActionLink("Search", "Search", "OrmLite")</button>

ASPNETWebApplicationTest/Views/OrmLite/Read.cshtml
@model ASPNETWebApplicationTest.Models.SimpleModels

@{
    ViewBag.Title = "Read";
}    

<h2>Read</h2>
<div>
    <h4>SimpleModel</h4>
    <hr />
    @foreach (var item in Model.simpleModel)
    {

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
    }
</div>

ASPNETWebApplicationTest/Views/OrmLite/Search.cshtml
@using ASPNETWebApplicationTest.Models

@model SimpleModel

@{
    ViewBag.Title = "Details";
}
<h2>Create</h2>
<div class="form-horizontal">
    @using (Html.BeginForm())
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
            <input type="submit" value="Search" class="btn btn-default"/>
        </div>
    }
    <div>
        <p> Name: @Model.Name <br /></p>
        <p> Description: @Model.Description <br /></p>
    </div>
    @Html.ActionLink("Back to List", "Index")
</div>